export { Hero } from './Hero'
export { Features } from './Features'
export { Progress } from './Progress'
export { Testimonials } from './Testimonials'
export { CTA } from './CTA'
export { Footer } from './Footer'